### ISSUE TITLE
Estruturação das pastas

### ISSUE THREAD

**Issue by fvieir** [ronaldof16/Copa-do-mundo-2022#1]
Fala Ronaldo, como vai?

Conforme deixado o Feedback e orientações no Discord, segue minha solicitação para a estruturação das pastas,criando uma pasta assets e dentro dela criar pasta para css e js e outras se necessárias.

Forte abraço.

**Comment by ronaldof16** [comment]
Obrigado Fabrício, feito.

**Comment by fvieir** [comment]
Ronaldo seu arquivo index.html ele tem que ficar na raiz do seu projeto fora da pasta html.

O index é o primeiro arquivo a ser executando assim é necessário coloca-lo na raiz do projeto para que seu projeto carregue.

Os outros arquivos html você pode manter na pasta.

Esse é o modelo a ser seguindo.

![image](https://user-images.githubusercontent.com/65264206/197423664-056549ce-2a81-4cc2-9c95-e4c1b034355d.png)
